snackbar added
akash-1318/MilkywayUI pull request #10
Opened 2022-02-07 19:52 UTC by akash-1318

2022-02-08 10:56 UTC, yogesh- reviewed
Looks good to merge

2022-02-09 06:44 UTC, ark2002 requested changes
please look into the suggested changes

2022-02-09 06:44 UTC, ark2002 commented on components/Snackbar.html
> +                    <div class="component__view">
rather than using comp__detail-text you can use your name convention of component__detail-text why change it for just one class

2022-02-09 06:44 UTC, ark2002 commented on components/Snackbar.html
> +                            <i class='bx bx-x'></i>
instead o using first para and second para you can use snackbar__title and snackbar__subtitle

2022-02-09 06:44 UTC, ark2002 commented on components/css/componentStyle/Snackbar.css
> +}
dont mix hex and rgb color codes

2022-02-09 06:44 UTC, ark2002 commented on components/css/componentStyle/Snackbar.css
> +
umm choose one color pattern and follow it dont mix those up

2022-02-09 06:44 UTC, ark2002 commented on components/css/main.css
>      --font-color: rgb(70, 70, 70);
here aswell why just one rgb rest hex

2022-02-09 07:09 UTC, merged